correct_artist_name = {
    "3D":"3D",
    "Banksy":"Banksy",
    "Basquiat Jean-Michel":"Jean-Michel Basquiat",
    "le Rat Blek":"Blek le Rat",
    "Braque Georges":"Georges Braque",
    "Ekster Aleksandra":"Aleksandra Ekster",
    "Lissitzky El":"El Lissitzky",
    "El Lissitzky":"El Lissitzky",
    "Escher M.C.":"M.C. Escher",
    "Kahlo Frida":"Frida Kahlo",
    "Kandinsky Wassily":"Wassily Kandinsky",
    "Klee Paul":"Paul Klee",
    "Lichtenstein Roy":"Roy Lichtenstein",
    "Magritte Rene":"Rene Magritte",
    "Malevich Kazimir":"Kazimir Malevich",
    "Phase 2":"Phase 2",
    "Picasso Pablo":"Pablo Picasso",
    "Pollock Jackson":"Jackson Pollock",
    "Rozanova Olga":"Olga Rozanoa",
    "TAKI 183":"TAKI 183",
    "Warhol Andy":"Andy Warhol",
}
